mysite/blog/urls.py
# una vez creado las urls de esta app se agrega este archivo a urls del proyecto
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

# organizamos las usls por aplicaciones
app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    
    # agregando un listado de posts usando ListView de Django
    # esto simplifica la vista y permite usar el template_name y context_object_name que se encuentran en settings.py
    # esto es más eficiente y permite personalizar el template según sea necesario
    # path('', views.PostListView.as_view(), name='post_list'),

    # agregando un listado de posts por tag
    path(
        'tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'
    ),
    # editando los campos para que sean unicos y agregando SEO
    path(
        '<int:year>/<int:month>/<int:day>/<slug:post>/', 
         views.post_detail, 
         name='post_detail'
    ),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path(
        '<int:post_id>/comment/', views.post_comment, name='post_comment'
    ),
    path('feed/', LatestPostsFeed(), name='post_feed'), # agregando el feed de la aplicacion   
    path('search/', views.post_search, name='post_search'), # agregando la busqueda de la aplicacion
]

mysite/mysite/urls.py
from django.contrib import admin
# se importa el sitemap para poder utilizarlo en las urls
from django.contrib.sitemaps.views import sitemap
# include para agregar la aplicacion blog
from django.urls import path, include
# se importa el sitemap de la aplicacion blog
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    # agregar el namespace de blog para poder usar urls relativas en blog.urls
    # se agrega el namespace como el nomre de la aplicacion
    # se refieren a los urls de la siguiente manera ej: blog:post_list
    path('blog/', include('blog.urls', namespace='blog')),
    # se agrega la url del sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

mysite/blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
# para crear get_absolute_url
from django.urls import reverse
# libreria para tags
from taggit.managers import TaggableManager

# Create your models here.

# definiendo un nuevo manager que hereda de models.Manager
class PublishedManager(models.Manager):
    # sobreescribimos el metodo para cuando realizamos 
    # cualquier consulta queryset esta ya solo obtenga los valores PUBLISHED
    def get_queryset(self):
        return (
            super().get_queryset().filter(status=Post.Status.PUBLISHED)
        ) 

class Post(models.Model):
    # similar a enum module
    # Uso Post.Status.values obtenemos valores
    # Post.Status.labels obtenemos los nombres
    class Status(models.TextChoices):
        # DF es el valor y Draft son labels readble
        # DRAFT es el nombre de la propiedad con el cual 
        # es conocido en el lenguaje python
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'


    title = models.CharField(max_length=250)
    # se guarda en str en la base de datos ayuda al SEO
    slug = models.SlugField(
        max_length=250,
        # unique_for_date se utiliza para evitar que un post con el mismo titulo
        # y fecha de publicacion sean iguales
        unique_for_date='publish'
        )

    author = models.ForeignKey(
        # tabla usuarios de la autenticacion de django
        settings.AUTH_USER_MODEL,
        # cuando se borre un usuario sus posts tambien lo hacen
        on_delete=models.CASCADE,
        # nos permite la relacion inversa acceder a los posts desde el usuario
        # user.blog_posts
        related_name='blog_posts'
    )

    body = models.TextField()
    # se guarda com DATETIME en SQL
    # timezon y su funcion son de lo importado de django
    publish = models.DateTimeField(default=timezone.now)
    # este campo se crea automaticamente cuando se crea el post
    created = models.DateTimeField(auto_now_add=True)
    # se usa augo_now para actualizar la fecha cuando se guarda un objeto
    updated = models.DateTimeField(auto_now=True)
    # creamos un nuevo campo si este post es un borrador df o publicado PB
    # por defecto DRAFT y que tiene dos opciones
    # crear la clase Status es una buena practica 
    status = models.CharField(
        max_length=2,
        choices=Status,
        default=Status.DRAFT,
    )

    # NOTA: en Meta podemos definir un manager por defecto
    # por defecto esta objects manager
    # por buena practica recordamos que el manager obbjects esta disponible
    objects = models.Manager() # the default manager
    # creamos un ojeto de nuestra clase creada PublishedManager
    published = PublishedManager()  # our custom manager

    # tags
    tags = TaggableManager()

    # meta es una clase dentro del modelo que tiene valores por defecto
    # los cuales actuan como propiedades extra del modelo
    class Meta:
        # se ordena los posts por fecha de publicacion en orden descendiente
        # se utiliza el - para que se ordenen en orden descendiente
        # este orden es por default si al hacer un query no se especifica
        ordering = ['-publish']
        # realizamos un index para mejorar la velocidad del ordenamiento
        indexes = [
            models.Index(fields=['-publish'])
        ]

    # nombre del objeto por titulo
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse(
            'blog:post_detail', # obtenido de blog.urls.py
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        # relacion inversa para acceder a los comentarios de un post comment.post
        # si no se da un related_name se crea uno por defecto comment_set
        related_name='comments'
    )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        # se crea un index para mejorar la velocidad de ordenamiento
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

mysite/blog/forms.py
from django import forms
# importamos el modelo Comment para poder usarlo en el formulario
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

# se crea un formulario para los comentarios con el modelo Comment
# se hereda de forms.ModelForm
class CommentForm(forms.ModelForm):
    # se define la clase Meta para el modelo Comment
    class Meta:
        model = Comment
        # se definen los campos que se mostraran en el formulario
        # estos campos se obtienen del modelo Comment
        fields = ('name', 'email', 'body')

class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
# importando el modelo
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
# importamos search de postgres
from django.contrib.postgres.search import (
    SearchQuery, SearchRank, SearchVector
)
# esto se puede editando el archivo de migraciones
from django.contrib.postgres.search import TrigramSimilarity # importamos TrigramSimilarity para buscar posts similares
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
# uso de decoradores
from django.views.decorators.http import require_POST
from taggit.models import Tag # importamos el modelo Tag
from django.db.models import Count # importamos Count para contar los tags

# from django.http import Http404




class PostListView(ListView):
    """
    Alternative post list view
    """
    queryset = Post.published.all()
    # nombre del contexto que se pasara a la plantilla
    # por defecto es object_list
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'
    # pasa las paginas al template como page=page_obj


# Create your views here.

# objeto request es requerido en todas las vistas
def post_list(request, tag_slug=None):
    # obteniendo una lista de posts
    post_list = Post.published.all()
    # objeto numero de posts por pagina
    tag = None
    # si se pasa un tag_slug se filtra por tag
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list, 3)
    # obteniendo el numero de la pagina el (,1) es por defecto
    page_number = request.GET.get('page', 1)
    try:
        # retornamos los posts de la pagina
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # si no es un numero entero retornamos la primera pagina
        posts = paginator.page(1)
    except EmptyPage:
        # si la pagina no existe retornamos la ultima
        # paginator.num_pages el numero de paginas es el mismo que la ultima pagina
        posts = paginator.page(paginator.num_pages)

    # renderizar la plantilla con los posts
    return render(
        request, 
        'blog/post/list.html', 
        {
            'posts': posts,
            'tag': tag
         }
    )

def post_detail(request, year, month, day, post):
    # retorna el post si cumple los parametros, publicado e id
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,  # solo mostramos posts publicados
        # obtenemos el objeto si este cumnple con lo siguiente 
        slug=post,  # slug es el nombre en minuscula con guiones intermedios
        # esto es posible por unique_for_date='publish' en el modelo
        publish__year=year,
        publish__month=month,
        publish__day=day  # fecha publicada en el post
    )

    # lista de comentarios activos para este post
    # acceedemos a los comentarios por post.comments ya que se relacionaron en el modelo
    comments = post.comments.filter(active=True)
    # inicializamos el formulario
    form = CommentForm()

    # lista de tags del post
    # flat=True para obtener una lista de valores en lugar de objetos
    post_tags_ids = post.tags.values_list('id', flat=True)
    # obtenemos los posts que contienen los mismos tags
    # excluimos el post actual
    similar_posts = Post.published.filter(
        tags__in=post_tags_ids
    ).exclude(id=post.id)
    # contamos los tags en comun y ordenamos por tags y fecha de publicacion
    similar_posts = similar_posts.annotate(
        same_tags=Count('tags')
    ).order_by('-same_tags', '-publish')[:4]

    # ubicacion del template y tambien mandamos el objeto post
    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'form': form,
            'similar_posts': similar_posts
        }
    )


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    # variable que enviaremos si es que se envio el formulario
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            # ... send email
            # obtenemos la url absoluta del post
            post_url = request.build_absolute_uri(
                post.get_absolute_url()
            )
            subject = (
                f"{cd['name']} ({cd['email']}) "
                f"recommends you reading {post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'s comments: {cd['comments']}"
            )
            # enviamos el email en la forma del objeto de la libreria de django
            send_mail(
                subject,
                message,
                from_email=None,
                recipient_list=[cd['to']]
            )
            sent = True


    else:
        # renderizamos el formulario vacio
        form = EmailPostForm()
    return render(
        request,
        'blog/post/share.html',
        {
            'post': post,
            'form': form,
            'sent': sent
        }
    )

# decorador para que solo se pueda acceder por POST
@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(
        Post,
        id=post_id,
        status=Post.Status.PUBLISHED
    )
    # variable que enviaremos si es que se envio el formulario
    comment = None
    # si se envio el formulario
    form = CommentForm(request.POST)
    if form.is_valid():
        # se crea un objeto de tipo comment pero no se guarda en la base de datos
        comment = form.save(commit=False)
        # asignamos el post al comentario
        comment.post = post
        comment.save()
    return render(
        request,
        'blog/post/comment.html',
        {
            'post': post,
            'comment': comment,
            'form': form
        }
    )

def post_search(request):
    form = SearchForm()
    query = None
    results = []

    # si se envio el formulario de busqueda y es valido se realiza la busqueda
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector(
                'title', weight='A' # titulo con peso A y cuerpo con peso B (1 y 0.4) respectivamente
            ) + SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = (
                # anotamos el campo search con el vector de busqueda
                Post.published.annotate(
                    similarity = TrigramSimilarity('title', query) # calculamos la similitud con el titulo
                )
                .filter(similarity__gt=0.1) # filtramos los resultados con una similitud mayor a 0.1
                .order_by('-similarity') # ordenamos por rank de mayor a menor
            )
    return render(
        request,
        'blog/post/search.html',
        {
            'form': form,
            'query': query,
            'results': results
        }
    )

mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}Add a comment{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {# post.body es un campo de texto largo #}
    {# markdown es un filtro que convierte el texto en HTML #}
    {# el filtro safe evita que se escape el HTML #}
    {{ post.body|markdown }}

    <p>
        <a href="{% url "blog:post_share" post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        <p>No similar posts yet.</p>
    {% endfor %}

    {# comments querySet de django ORM #}
    {# el with nos permite asignar un valor a una nueva variable hasta endwith #}
    {% with comments.count as total_comments %}
    <h2>
        {# aqui solo imprimimos un contador de cuantos comentarios hay #}
        {# pluralize aumenta una s si hay 0 o mas de 1 comentario #}
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
    {% endwith %}

    {# renderizamos los comentarios #}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                {# contiene el contador de cada iteracion #}
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {# es un tag de si esta vacio (no hay comentarios) #}
    {% empty %}
        <p>There are no comments.</p>
    {% endfor %}

    {# incluimos el formulario de comentarios #}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{# heredamos de base.html #}
{% extends "blog/base.html" %}
{# cargamos los tags #}
{% load blog_tags %}

{# titulo de la pagina #}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
        <h2>
            {# cambiando las urls dinamicas por absolutas #}
            {# el objeto post tiene su url #}
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        {# tags es un campo many to many #}
        {# join es un filtro de django que une los tags con una coma #}
        <p class="tags">
            Tags: 
            {% for tag in post.tags.all %}
                {# cada tag tiene su url #}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                    {# si no es el ultimo tag, ponemos una coma #}
                </a>{% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {# markdown es un filtro que convierte el texto en HTML #}
        {# el filtro truncatewords_html corta el texto en 30 palabras #}
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {# incluimos la paginacion #}
    {# el objeto posts tiene el paginador #}
    {# incluimos el template pagination.html #}
    {# pasamos el objeto posts a la variable page #}
    {% include "pagination.html" with page=posts %}
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
            Found {{ total_results }} result{{ total_results|pluralize:"s" }}.
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %} 
{% block title %}Share a post{% endblock %} 
{%block content %} 
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {# form.as_p decimos a django que rederice en un parrafo y token de seguridad #}
            {{ form.as_p }} 
            {% csrf_token %}
            <input type="submit" value="Send e-mail" />
        </form>
    {% endif %} 
{% endblock %}